name: ml
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - altair
  - ipykernel
  - keras
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - plotly
  - polars
  - python=3.8
  - seaborn
  - pyarrow
  - pytorch
  - pytorch-lightning
  - torchaudio
  - torchinfo
  - torchvision
  - tqdm
  - xarray
  - zarr
  - pip:
    - drawdata
    - gdown
    - ptpython
    - tensorflow