name: gis
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - fiona
  - gdal
  - geojson
  - geopandas
  - keplergl
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - polars
  - rasterio
  - shapely
  - xarray-spatial