name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipyparallel
  - jupyterlab
  - nb_conda_kernels
  - notebook
  - pip
  - pip:
    - ipyflow
    - jupyter_contrib_nbextensions
    - mitosheet