name: cml
channels:
  - rapidsai
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.6.0
  - cudf
  - cuml
  - dask
  - dask-cuda
  - dask-cudf
  - gputil
  - h5netcdf
  - h5py
  - kmodes
  - netCDF4
  - opencv
  - openpyxl
  - pygments
  - pytorch=1.12.0
  - pytorch-lightning
  - scikit-image
  - scikit-learn
  - scipy
  - torchaudio
  - torchinfo
  - torchvision
  - pip:
    - --no-binary=horovod
    - bentoml==1.0.5
    - deepchecks[vision]==0.10.0
    - great_expectations
    - horovod[pytorch]==0.25.0
    - merlin-dataloader==0.0.4
    - nebullvm==0.4.3
    - nvidia-ml-py==11.525.84
    - psycopg2-binary==2.9.3
    - segmentation-models==1.0.1
    - torchviz==0.0.2
    - truss==0.0.23