name: viz
channels:
  - pyviz
  - bokeh
  - plotly
  - conda-forge
  - defaults
dependencies:
  - altair
  - altair_saver
  - bokeh
  - datashader
  - holoviews
  - hvplot
  - geoviews
  - jupyter_bokeh
  - lumen
  - matplotlib
  - matplotlib-inline
  - networkx
  - panel
  - plotly
  - seaborn
  - vega_datasets