name: 'Hello World'

description: 'Greet someone and record the time'

inputs:
  image-name:
    description: 'Image name'
    required: true
    default: 'base'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.image-name }}