name: Build and push BASE image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: base

on:
  push:
    branches:
      - master
    paths:
      - '**/Dockerfile.${{ env.IMAGE_NAME }}'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - run: echo "${{ github.actor }}/${{ env.IMAGE_NAME }} will be built and pushed to ${{ env.REGISTRY }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          cd dev-with-containers && make ${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}