name: Build and push DEV

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dev
  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'dev-with-containers/Dockerfile.dev'
      - 'dev-with-containers/config/.theme.omp.json'
      - 'dev-with-containers/provision/neovim/**'
      - 'dev-with-containers/provision/scripts/**'
      - "!dev-with-containers/provision/scripts/install_aeneas.sh"
      - "!dev-with-containers/provision/scripts/install_coq.sh"
      - "!dev-with-containers/provision/scripts/install_ocaml.sh"
      - "!dev-with-containers/provision/scripts/install_provers.sh"
      - "!dev-with-containers/provision/scripts/install_ruby.sh"

jobs:
  dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "${{ github.actor }}/${{ env.IMAGE_NAME }} will be built and pushed to ${{ env.REGISTRY }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v1
      - name: Build and push ${{ env.IMAGE_NAME }} image
        uses: ./.github/actions/build-and-push-image
        with:
          image-name: ${{ env.IMAGE_NAME }}