name: Hello World

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: FOOBAR

on:
  gollum

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v1

      - name: Build and push ${{ env.IMAGE_NAME }} image
        uses: ./.github/actions/build-and-push-image
        with:
          image-name: ${{ env.IMAGE_NAME }}