name: Image Maintenance

env:
    ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:
    delete-untagged-images:
        permissions:
          packages: write
    
        name: Delete Untagged Images
        runs-on: ubuntu-latest
        steps:
            - name: Prune
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                user: jhwohlgemuth
                container: base
                keep-last: 1
                prune-untagged: true
              