name: Image Maintenance

env:
    ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          owner: jhwohlgemuth
          name: base
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: 1