name: Image Maintenance

env:
    ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    KEEP_UNTAGGED_COUNT: 1
    USER: jhwohlgemuth

on:
  workflow_dispatch:

jobs:
    delete-untagged-images:
        permissions:
          packages: write
    
        name: Delete Untagged Images
        runs-on: ubuntu-latest
        steps:
            - name: Prune Base
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: base
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true

            - name: Prune Notebook
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: notebook
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true

            - name: Prune Python
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: python
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true

            - name: Prune Rust
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: rust
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true

            - name: Prune JVM
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: jvm
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true

            - name: Prune Web
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: web
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true

            - name: Prune DOTNET
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: dotnet
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true

            - name: Prune Lambda
              uses: vlaurin/action-ghcr-prune@v0.5.0
              with:
                container: lambda
                token: ${{ env.ACCESS_TOKEN }}
                user: ${{ env.USER }}
                keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
                prune-untagged: true